### ISSUE TITLE
Password?!

### ISSUE THREAD

**Issue by Holygariii** [gap-system/bob#2]
I followed your suggestions on how to download GAP for Mac OS Sierra

1) Download Xcode
2) There's no "Downloads" pane in my Xcode, but I have the Command Line Tools Xcode 8.3.3.
3) Downloaded MacPorts 2.4.1.

Now my problem is typing this in my Terminal

% sudo port install readline +universal ncurses +universal gawk wget xorg-libX11 xorg-libXaw

It keeps on giving me "Password". 
<img width="577" alt="screen shot 2017-07-15 at 2 27 02 pm" src="https://user-images.githubusercontent.com/30192116/28237091-c2eff348-6969-11e7-89e7-e53d2651e9e1.png">

**Comment by ChrisJefferson** [comment]
That is your own password which you use to log in with. You need to enter your password whenever you run `sudo`.

**Comment by Holygariii** [comment]
OMG! Thank you! No wonder I can't proceed. sudo doesn't allow blank
password.

**Comment by alex-konovalov** [comment]
Hop you figured out what to do. Please note that BOB installer does not offer latest GAP any more - you need to install it from [source](https://www.gap-system.org/Releases/) or use other [alternatives](https://www.gap-system.org/Download/alternatives.html), like e.g. Homebrew.

**Comment by Holygariii** [comment]
I realised that BOB is no longer updated yesterday when I visited GAP.
Unfortunately, I have already installed the packages included in

% sudo port install readline +universal ncurses +universal gawk wget
xorg-libX11 xorg-libXaw

Should I uninstall MacPorts, will these packages also be uninstalled? That
way, I could reinstall GAP properly from the source or Homebrew.

**Comment by alex-konovalov** [comment]
If you installed those dependencies with MacPorts and then used BOB to install some (not the latest) version of GAP, you can perhaps equally install the latest GAP release from source - dependencies provided by MacPorts will be already satisfied. The approach of removing MacPorts (unless you need it for other stuff) and then doing a new install with Homebrew will also work. I've used both on the same machine in the past, and that worked for me too (https://www.reddit.com/r/macsysadmin/comments/59n19p/homebrew_and_macports_on_the_same_machine/).
